-- ============================================================
--  CRD - Central Record Directory (NYUC)
--  Supabase schema + storage. Run this once in the Supabase
--  SQL editor. Safe to re-run (IF NOT EXISTS everywhere).
-- ============================================================

-- ---------- SESSIONS (login handshake with the bot) ----------
create table if not exists crd_sessions (
  id          bigint generated by default as identity primary key,
  token       text unique not null,
  code        text,
  active      boolean default false,
  denied      boolean default false,
  remember    boolean default false,
  discord_id  text,
  username    text,
  is_whitelist boolean default false,
  created_at  timestamptz default now()
);
create index if not exists crd_sessions_code_idx on crd_sessions (code);
create index if not exists crd_sessions_discord_idx on crd_sessions (discord_id);

-- ---------- ACCESS (who the bot granted, via /crdmanage) ----------
create table if not exists crd_access (
  discord_id  text primary key,
  username    text,
  granted_by  text,
  granted_at  bigint
);

-- ---------- COUNTERS (case numbering) ----------
create table if not exists crd_counters (
  key   text primary key,
  value integer default 0
);

-- ---------- STAFF PROFILES ----------
create table if not exists crd_staff (
  id             bigint generated by default as identity primary key,
  discord_id     text,
  username       text not null,
  position       text,
  category       text default 'active',      -- active | inactive | before_revamp | archived
  join_date      text,
  approx_era     text,
  roblox_username text,
  roblox_id      text,
  notes          text,
  classified     boolean default false,
  documents      jsonb default '[]'::jsonb,  -- attached files (see uploads)
  added_by       text,
  created_at     timestamptz default now()
);
create index if not exists crd_staff_category_idx on crd_staff (category);

-- ---------- CASES ----------
create table if not exists crd_cases (
  id              bigint generated by default as identity primary key,
  number          text unique not null,
  category        text default 'active',     -- active | inactive | before_revamp | archived
  subject_id      text,
  subject_username text default 'Unknown',
  date_opened     bigint,
  approx_date     text,
  subject_matter  text,
  testimony       text,
  status          text,
  classified      boolean default false,
  confidentiality text default 'internal',            -- public|internal|restricted|confidential|secret
  locked          boolean default false,
  locked_by       text,
  locked_at       bigint,
  department      text,
  lead            text,
  priority        text,
  outcome         text,
  tags            jsonb default '[]'::jsonb,
  proof           jsonb default '[]'::jsonb,          -- evidence files (any format)
  documents       jsonb default '[]'::jsonb,          -- authorization / paperwork files
  authorizations  jsonb default '[]'::jsonb,          -- who is authorized on this case
  source          text,
  added_by        text,
  created_at      timestamptz default now()
);
create index if not exists crd_cases_category_idx on crd_cases (category);

-- If you already had crd_cases / crd_staff, add the new columns:
alter table crd_cases  add column if not exists documents      jsonb default '[]'::jsonb;
alter table crd_cases  add column if not exists authorizations jsonb default '[]'::jsonb;
alter table crd_cases  add column if not exists proof          jsonb default '[]'::jsonb;
alter table crd_cases  add column if not exists locked         boolean default false;
alter table crd_cases  add column if not exists locked_by      text;
alter table crd_cases  add column if not exists locked_at      bigint;
alter table crd_cases  add column if not exists confidentiality text default 'internal';
alter table crd_cases  add column if not exists department     text;
alter table crd_cases  add column if not exists lead           text;
alter table crd_cases  add column if not exists priority       text;
alter table crd_cases  add column if not exists tags           jsonb default '[]'::jsonb;
alter table crd_cases  add column if not exists outcome        text;
alter table crd_cases  add column if not exists source         text;
alter table crd_staff  add column if not exists documents      jsonb default '[]'::jsonb;
alter table crd_staff  add column if not exists source         text;
alter table crd_access add column if not exists username       text;

-- IMPORTANT: after adding columns, reload the PostgREST schema cache so the
-- API sees them immediately (otherwise you get "Could not find the 'x' column").
notify pgrst, 'reload schema';

-- ---------- AUDIT (every read/write worth logging) ----------
create table if not exists crd_audit (
  id         bigint generated by default as identity primary key,
  action     text,
  actor_id   text,
  actor_name text,
  detail     text,
  created_at timestamptz default now()
);

-- ============================================================
--  STORAGE  (proof + documents, all file formats)
-- ============================================================
--  A single PRIVATE bucket. Files are uploaded with a signed
--  upload URL and read back with a short-lived signed URL, both
--  minted server-side by the Netlify functions (service key).
--  Nothing is publicly listable.
insert into storage.buckets (id, name, public)
values ('crd-files', 'crd-files', false)
on conflict (id) do nothing;

-- (No public storage policies on purpose: only the service key,
--  used exclusively inside the Netlify functions, can touch it.)
